name: flutter_acrcloud_plugin
description: A Flutter plugin that enables music recognition in your Flutter apps using the ACRCloud API. Easily identify music from microphone input with a simple Dart interface.
version: 0.0.1
homepage: https://github.com/nixxel-company-limited/flutter_acrcloud

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0

flutter:
  plugin:
    platforms:
      android:
        package: com.nrubintech.flutter_acrcloud
        pluginClass: FlutterAcrcloudPlugin
      ios:
        pluginClass: FlutterAcrcloudPlugin

keywords:
  - flutter_acrcloud_plugin
  - acr_cloud
  - flutter
  - music
  - recognition
  - audio
